---
- name: Configure nginx web-server with TLS support
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: Install nginx
      apt:
        name=nginx

    - name: Create directory for SSL
      file:
        path=/etc/nginx/ssl
        state=directory

    - name: Copy TLS keys
      copy:
        src=files/nginx.key
        dest={{ key_file  }}
        owner=root
        mode=0600
      notify: restart nginx

    - name: Copy TLS certs
      copy:
        src=files/nginx.crt
        dest={{ cert_file  }}
      notify: restart nginx

    - name: Copy config nginx file
      template:
        src=templates/nginx.conf.j2
        dest={{ conf_file  }}
      notify: restart nginx

    - name: Enable Configuration
      file:
        dest=/etc/nginx/sites-enabled/default
        src={{ conf_file  }}
        state=link
      notify: restart nginx

    - name: Copy index.html
      template:
        src=templates/index.html.j2
        dest=/usr/share/nginx/html
        mode=0644

  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=restarted
